INSERT INTO CUSTOMER VALUES(1,'Korey Rodi');
INSERT INTO ADDRESS VALUES('work', 'Cecil B Moore',1727, 'Philadelphia', 'PA',19121,1);
INSERT INTO CAR_TYPE VALUES(1, 'this is my car');
INSERT INTO CAR VALUES(123456,'mazda', 'mazda 6', 1);
INSERT INTO RENTAL VALUES(1,TO_DATE('12/25/2025', 'MM/DD/YYYY'),TO_DATE('12/27/2025', 'MM/DD/YYYY'),600,1,123456);
INSERT INTO PREFERENCE VALUES(1,1,1);
INSERT INTO FEATURE VALUES(1,'Sun Roof',123456);
INSERT INTO PAYMENT VALUES(1,TO_DATE('12/27/2025','MM/DD/YYYY'), TO_TIMESTAMP('12:00 AM', 'HH:MI AM'), 600,1);

commit;
/*
SELECT * FROM ADDRESS;
SELECT * FROM CAR;
SELECT * FROM CAR_TYPE;
SELECT * FROM CUSTOMER;
SELECT * FROM FEATURE;
SELECT * FROM PAYMENT;
SELECT * FROM PREFERENCE;
SELECT * FROM RENTAL;
*/